---
# tasks file for loadbalancer

- name: Set timezone
  timezone:
    name: "{{ nginx_timezone }}"

- name: Install Nginx key
  apt_key:
    id: "{{ nginx_apt_keyid }}"
    url: "{{ nginx_apt_key }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/ansible.gpg
  register: nginx_key_install
  until: nginx_key_install is success
  retries: 3
  delay: 2

- name: Add official Nginx repository
  apt_repository:
    repo: "{{ nginx_apt_list }}"
    state: present
    filename: "nginx"

- name: Install nginx
  apt:
    name: "{{ package }}"
    state: present
    update_cache: true
  register: nginx_install
  until: nginx_install is success
  retries: 3
  delay: 2

- name: Remove default config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Setup our load balancing configuration
  template:
    src: loadbalancer.conf
    dest: /etc/nginx/conf.d/loadbalancer.conf
  notify: restart nginx
