---
# tasks file for loadbalancer

- name: Install Nginx key
  apt_key:
    id: "{{ nginx_apt_keyid }}"
    url: "{{ nginx_apt_key }}"
    state: present
    keyring: /etc/apt/trusted.gpg.d/ansible.gpg

- name: Add official Nginx repository
  apt_repository:
    repo: "{{ nginx_apt_list }}"
    state: present
    filename: "nginx"

- name: Install nginx
  apt:
    name: "{{ package }}"
    state: latest
    update_cache: true

- name: Remove default config
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Setup our load balancing configuration
  template:
    src: loadbalancer.conf
    dest: /etc/nginx/conf.d/loadbalancer.conf
  notify: restart nginx